### PR TITLE
Split functions into individual files

### PR DESCRIPTION
**Pull request by scorphus**
Reference oh-my-fish/oh-my-fish#8

### CODE REVIEW

**Comment by derekstavis** [comment]
LGTM :+1:

**Comment by bobthecow** [comment]
:+1:

**Comment by bpinto** [comment]
I wouldn't split private functions as they are private, they wouldn't be called from anywhere else but the file they were written.

**Comment by bobthecow** [comment]
good point.

**Comment by scorphus** [comment]
Agreed.

**Comment by scorphus** [comment]
But even so, in this case, it makes initialization a bit faster. `bundler` declares as much functions as included in `execs`. All those functions will eventually call those other _private_. But they don't need to be loaded on `init`, they should be lazy-loaded.

**Comment by bpinto** [comment]
Perhaps the functions have public scope then?

**Comment by scorphus** [comment]
Yeah, that makes sense. Let me amend that as soon as I can.

**Comment by scorphus** [comment]
Thinking a bit more over it, I believe those two are still `private` functions, not plugin-wise, but fish-wise. What do you think we renaming `s/^__/_/` they? A diff is worth a thousand words:

**Comment by bpinto** [comment]
I have thought about it but I believe they are public, wouldnt it be the same for me to call bundle-execute on the prompt as the plugin is doing with these new generated functions?

**Comment by scorphus** [comment]
Yeah, but it wouldn't make much sense calling it directly. Why not add those function names to `bundler_plugin_execs` in the first place?

**Pull request merged**
